config/routes.rb
Rails.application.routes.draw do
#   devise_for :users, controllers: {
#   omniauth_callbacks: "omniauth_callbacks"
# }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # google
  post '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/signout' => 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  #ゲスト
  post 'guest_login', to: "guest_sessions#create"

  resources :users do
    collection {post :import}
    resources :scores do
      resources :beats
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
   
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    
end

app/views/static_pages/top.html.erb
<% provide(:title, "Top") %>
<div class="container container-m">
<div class="center jumbotron">
  <h1>ギターコード譜エディタ</h1>
  <p>このアプリケーションでは、登録された楽譜の勤怠情報を閲覧、登録、編集することができます。</p>
  <%= link_to "ユーザー登録", signup_path, class: "btn btn-lg btn-primary" %>
</div>
</div>

<%# <p>jQuery稼働テスト</p>
<script type="text/javascript">
  $(document).ready(function() {
    $("p").text("jQuery稼働テスト(稼働中)");
  });
</script>
<h2>CSSが適応されると色が変わる</h2>
<button type="button" class="btn btn-primary">Bootstrap適応</button> %>