config/routes.rb
Rails.application.routes.draw do
#   devise_for :users, controllers: {
#   omniauth_callbacks: "omniauth_callbacks"
# }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # google
  post '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/signout' => 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  #ゲスト
  post 'guest_login', to: "guest_sessions#create"

  resources :users do
    collection {post :import}
    resources :scores do
      resources :beats
    end
  end

end

app/models/score.rb
class Score < ApplicationRecord
    belongs_to :user
    has_many :beats, dependent: :destroy

    validates :title, presence: true
    validates :artist, presence: true
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :index, :edit, :update, :destroy]
  before_action :admin_or_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    @scores = Score.all
  end

  def show
    @i = 0
    if params[:create_id].present?
      @user = User.find(params[:create_id])
    else
      @user = User.find(params[:user_id])
    end  
    @score = @user.scores.find(params[:id])
    @beats = @score.beats.all
  end

  def new
    @user = User.find(params[:user_id])
    @score = @user.scores.new
  end
  
  def edit
    @user = User.find(params[:user_id])
    @score = @user.scores.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @score = @user.scores.find(params[:id])
    if @score.update(score_params)
      flash[:success] = "楽譜を更新しました。"
      redirect_to user_scores_url
    else
      render :edit      
    end
  end

  def create
    @user = User.find(params[:user_id])
    @score = @user.scores.new(score_params)
    if @score.save
      60.times do |n|
        @score.beats.create
        end
      flash[:success] = '新規作成に成功しました。'
      redirect_to user_scores_url
    else
      render :new
    end
  end

  def destroy
    @score = Score.find(params[:id])
    @score.destroy
    flash[:success] = "#{@score.title}のデータを削除しました。"
    redirect_to user_scores_url
  end

  private

  def score_params
    params.require(:score).permit(:title, :artist, :capo)
  end

  

end

app/views/scores/_edit_form.html.erb
<%= form_with(model: @score, url: user_score_path(), method: :patch, local: true) do |f| %>
<%= render 'shared/error_messages', object: @score %>
  <%= f.label :title, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :artist, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :artist, class: "form-control" %>
  <%= f.label :capo, class: "label-#{yield(:class_text)}" %>
  <%= f.select :capo, [["なし","なし"],["1フレット","1フレット"],["2フレット","2フレット"],["3フレット","3フレット"]], class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/scores/_form.html.erb
<%= form_with(model: @score, url: user_scores_path(), method: :post, local: true) do |f| %>
<%= render 'shared/error_messages', object: @score %>
  <%= f.label :title, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :artist, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :artist, class: "form-control" %>
  <%= f.label :capo, class: "label-#{yield(:class_text)}" %>
  <%= f.select :capo, [["なし","なし"],["1フレット","1フレット"],["2フレット","2フレット"],["3フレット","3フレット"]], class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/scores/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'scoreedit') %>
<% provide(:button_text, '更新') %>
<h1>楽譜の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'edit_form' %>
  </div>
</div>

app/views/scores/index.html.erb
<% provide(:title, 'All Scores') %>
<% provide(:class_text, 'score--edit') %>
<% provide(:button_text, '更新') %>
<h1>楽譜一覧</h1>
  <table class="table table-condensed table-hover" id="table-beats">
    <thead>
      <tr>
        <th>曲名</th>
        <th>アーティスト</th>
        <th></th>
      </tr>
    </thead>
      <% @scores.each do |score| %>
        <tr>
          <td><%= score.title %></td>
          <td><%= score.artist %></td>
          <td><%= link_to "閲覧", user_score_path(id: score.id, create_id: score.user_id), class: "btn btn-lg btn-warning" %>
          <% if current_user.id == score.user_id %>
            <%= link_to "修正", edit_user_score_path(id: score.id), class: "btn btn-lg btn-success" %>
            <%= link_to "削除", user_score_path(id: score.id), method: :delete, class: "btn btn-lg btn-danger" %>
          <% end %>
          </td>
        </tr>
      <% end %>
  </table>

  <%= link_to "新規作成", new_user_score_path, class: "btn btn-lg btn-primary" %>

app/views/scores/new.html.erb
<% provide(:title, 'score--new') %>
<% provide(:class_text, 'scorenew') %>
<% provide(:button_text, '新規作成') %>
<h1>楽譜作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/scores/show.html.erb
<% provide(:title, @score.title) %>
<h1><%= @score.title %></h1>
<p>アーティスト：<%= @score.artist %></p>
<p>カポ：<%= @score.capo %></p>
  <div>
  <table class="table table-bordered table-condensed score-table">
  </table>
  </div>
  <div>
  <table class="table table-condensed table-hover" id="table-beats">
    <thead>
      <tr>
        <th>拍子</th>
        <th>コード / 歌詞</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @beats.each do |beat| %>
        <tr>
          <td><%= @i += 1 %></td>
          <td><%= beat.image_name %><br>
              <% unless beat.image_name == nil %>
              <%= image_tag "/#{beat.image_name}.png" %>
              <% end %>
              <%= beat.lyric %></td>
        <% if @score.user_id == current_user.id %>      
          <td><%= link_to "設定", edit_user_score_beat_path(user_id: params[:user_id], score_id: beat.score_id, id: beat.id), class: "btn btn-lg btn-primary" %></td>
        <% else %>
          <td></td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>