config/routes.rb
Rails.application.routes.draw do
#   devise_for :users, controllers: {
#   omniauth_callbacks: "omniauth_callbacks"
# }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # google
  post '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/signout' => 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  #ゲスト
  post 'guest_login', to: "guest_sessions#create"

  resources :users do
    collection {post :import}
    resources :scores do
      resources :beats
    end
  end

end

app/models/beat.rb
class Beat < ApplicationRecord
  belongs_to :score
end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
    before_action :logged_in_user, only: [:new, :edit, :update]
    before_action :admin_or_correct_user, only: [:edit, :update]
  
    def new
      @score = Score.new
      60.times do |n|
        Beat.create!
        end
    end
    
    def edit
      @user = User.find(params[:user_id])
      @score = @user.scores.find(params[:score_id])
      @beat = @score.beats.find(params[:id])
    end
  
    def update
      @user = User.find(params[:user_id])
      @score = @user.scores.find(params[:score_id])
      @beat = @score.beats.find(params[:id])
      if @beat.update(lyric: params[:beat][:lyric], image_name: params[:beat][:image_name])
        flash[:success] = "歌詞を更新しました。"
        redirect_to user_score_url(id: params[:score_id])
      else
        render :edit      
      end
    end
  
  
    private
  
    def beat_params
      params.require(:beat).permit(:lyric)
    end
  
  end

app/views/beats/_edit_form.html.erb
<%= form_with(model: @beat, url: user_score_beat_path(), method: :patch, local: true) do |f| %>
  <%= f.label :lyric, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :lyric, class: "form-control" %>
  <%= f.label :image_name, class: "label-#{yield(:class_text)}" %>
  <%= f.select :image_name, [["選択してください","選択してください"],["Am7","Am7"],["C","C"],["C7","C7"],["E7","E7"],["E7onA♭","E7onA♭"],["Em7","Em7"],["F","F"],["G","G"],["Gm7","Gm7"]], class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/beats/_form.html.erb
<%= form_with(model: @beat, local: true) do |f| %>
  <%= f.label :lyric, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :lyric, class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/beats/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'beatedit') %>
<% provide(:button_text, '更新') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'edit_form' %>
  </div>
</div>