config/routes.rb
Rails.application.routes.draw do
#   devise_for :users, controllers: {
#   omniauth_callbacks: "omniauth_callbacks"
# }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # google
  post '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/signout' => 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  #ゲスト
  post 'guest_login', to: "guest_sessions#create"

  resources :users do
    collection {post :import}
    resources :scores do
      resources :beats
    end
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to("Guitar App", root_path,{class: "navbar-brand"}) %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <% unless logged_in? %>
        <%= link_to("ログイン", login_path,{class: "nav-link"}) %>
      <% end %>
      </li>
      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to("楽譜一覧", user_scores_path(current_user.id),{class: "nav-link"}) %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if current_user.admin? %>
          <%= link_to("一覧", users_path,{class: "dropdown-item"}) %>
        <% end %>
        <% unless current_user.name == "ゲストユーザー" || current_user.name == current_user.image_url %>
          <%= link_to("設定", edit_user_path(current_user),{class: "dropdown-item"}) %>
        <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to("ログアウト", logout_path, { method: :delete, data: {confirm: "ログアウトしますか？"}, class: "dropdown-item"}) %>
        </div>
      </li>
        
      
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><%= current_user.name %></a>
      </li>
    </ul>
    <% end %>
    <form class="form-inline my-2 my-lg-0">
      
    </form>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
 
    
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%# <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>